Update 42_custom_toolchains.md
With the version from before I get:

[nix-shell:~/build_rs_example/crate2nix]$ nix build .
warning: Git tree '/home/nixos/build_rs_example' is dirty
error: attribute 'appliedCargoNix' missing
       at /nix/store/jxd86xc1bimrdsa98z4c79ig3xfswn5v-source/crate2nix/flake.nix:17:22:
           16|           crate2nix' = pkgs.callPackage (import "${crate2nix}/tools.nix") {};
           17|           cargoNix = crate2nix.appliedCargoNix {
             |                      ^
           18|             name = "build_rs_example";


So maybe the appliedCargoNix function has moved from crate2nix (a valid output) into the crate2nix' OR it never worked.